name: Build
on:
  pull_request:
    branches: [master]
jobs:
  test:
    name: Tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: go test ./...
